=== ttngocson/OxygenXMLEditor/BaiKT04/QLKS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1">

    <xs:element name="QuanLyDatPhong">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Phong" maxOccurs="unbounded" minOccurs="5">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaPhong">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:pattern value="[0-9][0-9][0-9]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Tang">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:pattern value="[0-9][0-9]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="GiaNiemYet" type="xs:int"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="KhachHang" maxOccurs="unbounded" minOccurs="5">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaKH">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="KH[0-9][0-9][0-9]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="HoKH" type="xs:string"/>
                            <xs:element name="TenKH" type="xs:string"/>
                            <xs:element name="DiaChi" type="xs:string"/>
                            <xs:element name="SDT" type="xs:int"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="PhieuDatPhong" maxOccurs="unbounded" minOccurs="5">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaPhieu">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="PHIEU[0-9][0-9][0-9]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="MaKH">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="KH[0-9][0-9][0-9]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="NgayDatPhong" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ChiTietPhieu" maxOccurs="unbounded" minOccurs="5">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaPhieu">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="PHIEU[0-9][0-9][0-9]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="MaPhong">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:pattern value="[0-9][0-9][0-9]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="ThoiGianO">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="NgayDen" type="xs:date"/>
                                        <xs:element name="NgayDi" type="xs:date"/>

                                    </xs:sequence>
                                    <xs:assert test="NgayDi ge NgayDen"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="DonGIa" type="xs:int"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="KeyPhong">
            <xs:selector xpath="Phong"/>
            <xs:field xpath="MaPhong"/>
        </xs:key>
        <xs:key name="KeyKhachHang">
            <xs:selector xpath="KhachHang"/>
            <xs:field xpath="MaKH"/>
        </xs:key>
        <xs:key name="KeyPhieuDatPhong">
            <xs:selector xpath="PhieuDatPhong"/>
            <xs:field xpath="MaPhieu"/>
        </xs:key>
        <xs:key name="KeyCTPhieu">
            <xs:selector xpath="ChiTietPhieu"/>
            <xs:field xpath="MaPhieu"/>
            <xs:field xpath="MaPhong"/>
        </xs:key>
        <xs:keyref name="Phong-CTPhieu" refer="KeyPhong">
            <xs:selector xpath="ChiTietPhieu"/>
            <xs:field xpath="MaPhong"/>
        </xs:keyref>
        <xs:keyref name="Phieu-CTPhieu" refer="KeyPhieuDatPhong">
            <xs:selector xpath="ChiTietPhieu"/>
            <xs:field xpath="MaPhieu"/>
        </xs:keyref>
        <xs:keyref name="KH-DP" refer="KeyKhachHang">
            <xs:selector xpath="PhieuDatPhong"/>
            <xs:field xpath="MaKH"/>
        </xs:keyref>
    </xs:element>
</xs:schema>

=== ttngocson/OxygenXMLEditor/BaiKT04/QLKS.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="QLKS.xsl"?>
<QuanLyDatPhong xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="QLKS.xsd">
    <Phong>
        <MaPhong>101</MaPhong>
        <Tang>01</Tang>
        <GiaNiemYet>200000</GiaNiemYet>
    </Phong>
    <Phong>
        <MaPhong>102</MaPhong>
        <Tang>01</Tang>
        <GiaNiemYet>200000</GiaNiemYet>
    </Phong>
    <Phong>
        <MaPhong>201</MaPhong>
        <Tang>02</Tang>
        <GiaNiemYet>250000</GiaNiemYet>
    </Phong>
    <Phong>
        <MaPhong>202</MaPhong>
        <Tang>02</Tang>
        <GiaNiemYet>250000</GiaNiemYet>
    </Phong>
    <Phong>
        <MaPhong>301</MaPhong>
        <Tang>03</Tang>
        <GiaNiemYet>300000</GiaNiemYet>
    </Phong>
    <KhachHang>
        <MaKH>KH001</MaKH>
        <HoKH>Trần Như</HoKH>
        <TenKH>Nam</TenKH>
        <DiaChi>Nha Trang</DiaChi>
        <SDT>0986482654</SDT>
    </KhachHang>
    <KhachHang>
        <MaKH>KH002</MaKH>
        <HoKH>Lê Khánh</HoKH>
        <TenKH>Toàn</TenKH>
        <DiaChi>Cam Ranh</DiaChi>
        <SDT>0976653152</SDT>
    </KhachHang>
    <KhachHang>
        <MaKH>KH003</MaKH>
        <HoKH>Trần</HoKH>
        <TenKH>Lâm</TenKH>
        <DiaChi>Cam Ranh</DiaChi>
        <SDT>094632512</SDT>
    </KhachHang>
    <KhachHang>
        <MaKH>KH004</MaKH>
        <HoKH>Nguyễn Khánh</HoKH>
        <TenKH>An</TenKH>
        <DiaChi>Phan Rang</DiaChi>
        <SDT>0983202153</SDT>
    </KhachHang>
    <KhachHang>
        <MaKH>KH005</MaKH>
        <HoKH>Phan</HoKH>
        <TenKH>Hải</TenKH>
        <DiaChi>Cam Ranh</DiaChi>
        <SDT>0453126595</SDT>
    </KhachHang>
    <PhieuDatPhong>
        <MaPhieu>PHIEU001</MaPhieu>
        <MaKH>KH001</MaKH>
        <NgayDatPhong>2012-12-20</NgayDatPhong>
    </PhieuDatPhong>
    <PhieuDatPhong>
        <MaPhieu>PHIEU002</MaPhieu>
        <MaKH>KH002</MaKH>
        <NgayDatPhong>2013-07-11</NgayDatPhong>
    </PhieuDatPhong>
    <PhieuDatPhong>
        <MaPhieu>PHIEU003</MaPhieu>
        <MaKH>KH003</MaKH>
        <NgayDatPhong>2012-06-12</NgayDatPhong>
    </PhieuDatPhong>
    <PhieuDatPhong>
        <MaPhieu>PHIEU004</MaPhieu>
        <MaKH>KH004</MaKH>
        <NgayDatPhong>2012-02-21</NgayDatPhong>
    </PhieuDatPhong>
    <PhieuDatPhong>
        <MaPhieu>PHIEU005</MaPhieu>
        <MaKH>KH005</MaKH>
        <NgayDatPhong>2012-01-20</NgayDatPhong>
    </PhieuDatPhong>
    <ChiTietPhieu>
        <MaPhieu>PHIEU001</MaPhieu>
        <MaPhong>102</MaPhong>
        <ThoiGianO>
            <NgayDen>2013-02-20</NgayDen>
            <NgayDi>2013-02-21</NgayDi>
        </ThoiGianO>
        <DonGIa>200000</DonGIa>
    </ChiTietPhieu>
    <ChiTietPhieu>
        <MaPhieu>PHIEU001</MaPhieu>
        <MaPhong>101</MaPhong>
        <ThoiGianO>
            <NgayDen>2016-05-04</NgayDen>
            <NgayDi>2016-05-04</NgayDi>
        </ThoiGianO>
        <DonGIa>200000</DonGIa>
    </ChiTietPhieu>
    <ChiTietPhieu>
        <MaPhieu>PHIEU003</MaPhieu>
        <MaPhong>201</MaPhong>
        <ThoiGianO>
            <NgayDen>2012-01-20</NgayDen>
            <NgayDi>2012-02-25</NgayDi>
        </ThoiGianO>
        <DonGIa>250000</DonGIa>
    </ChiTietPhieu>
    <ChiTietPhieu>
        <MaPhieu>PHIEU004</MaPhieu>
        <MaPhong>301</MaPhong>
        <ThoiGianO>
            <NgayDen>2012-06-27</NgayDen>
            <NgayDi>2012-06-27</NgayDi>
        </ThoiGianO>
        <DonGIa>300000</DonGIa>
    </ChiTietPhieu>
    <ChiTietPhieu>
        <MaPhieu>PHIEU005</MaPhieu>
        <MaPhong>202</MaPhong>
        <ThoiGianO>
            <NgayDen>2012-08-20</NgayDen>
            <NgayDi>2012-08-21</NgayDi>
        </ThoiGianO>
        <DonGIa>450000</DonGIa>
    </ChiTietPhieu>
</QuanLyDatPhong>
