=== ttngocson/OxygenXMLEditor/catalog/SinhVien.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="QLSINHVIEN">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="SINHVIEN">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MASV"/>
                            <xs:element name="TENSV"/>
                            <xs:element name="GIOITINH">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="NAM|Ná»®"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="NGAYSINH"/>
                            <xs:element name="MALOP">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z][a-zA-Z][a-zA-Z][a-zA-Z][0-9][0-9]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ttngocson/OxygenXMLEditor/catalog/SinhVien.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="SinhVien.xsl"?>
<QLSINHVIEN xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="SinhVien.xsd">
    <SINHVIEN>
        <MASV>SV01</MASV>
        <TENSV>PHAN TUẤN CƯỜNG</TENSV>
        <GIOITINH>NAM</GIOITINH>
        <NGAYSINH>03/03/1993</NGAYSINH>
        <MALOP>CNTT16</MALOP>
    </SINHVIEN>
    <SINHVIEN>
        <MASV>SV02</MASV>
        <TENSV>HUỲNH CHÍ TÂM</TENSV>
        <GIOITINH>NAM</GIOITINH>
        <NGAYSINH>08/03/1993</NGAYSINH>
        <MALOP>CNTT16</MALOP>
    </SINHVIEN>
    <SINHVIEN>
        <MASV>SV03</MASV>
        <TENSV>VƯƠNG CHÍ DŨNG</TENSV>
        <GIOITINH>NAM</GIOITINH>
        <NGAYSINH>14/04/1991</NGAYSINH>
        <MALOP>CNTT16</MALOP>
    </SINHVIEN>
    <SINHVIEN>
        <MASV>SV04</MASV>
        <TENSV>PHẠM ĐỨC NGUYÊN</TENSV>
        <GIOITINH>NAM</GIOITINH>
        <NGAYSINH>27/07/1993</NGAYSINH>
        <MALOP>TCKT15</MALOP>
    </SINHVIEN>
    <SINHVIEN>
        <MASV>SV05</MASV>
        <TENSV>TRƯƠNG MỸ YẾN NHI</TENSV>
        <GIOITINH>NỮ</GIOITINH>
        <NGAYSINH>03/10/1993</NGAYSINH>
        <MALOP>TCKT15</MALOP>
    </SINHVIEN>
</QLSINHVIEN>
