=== ttngocson/OxygenXMLEditor/Thi/QLSach.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" vc:minVersion="1.1" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning">

    <xs:element name="QLSach">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="KhachHang" maxOccurs="unbounded" minOccurs="5">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaKH">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="KH[0-9][0-9][0-9]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="HoDemKH" type="xs:string"/>
                            <xs:element name="TenKH" type="xs:string"/>
                            <xs:element name="NgaySinh" type="xs:date"/>
                            <xs:element name="DiaChi" type="xs:string"/>
                            <xs:element name="DienThoai" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="LoaiSach" maxOccurs="unbounded" minOccurs="5">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaLoai">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="L[0-9][0-9]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="TenLoai" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Sach" maxOccurs="unbounded" minOccurs="5" nillable="false">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaSach">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="S[0-9][0-9][0-9]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="TenSach" type="xs:string"/>
                            <xs:element name="MaLoai">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="L[0-9][0-9]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="GiaThue">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ThueSach" maxOccurs="unbounded" minOccurs="5">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="NgayThue" type="xs:date"/>
                            <xs:element name="MaSach">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="S[0-9][0-9][0-9]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="MaKH">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="KH[0-9][0-9][0-9]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="NgayTra" type="xs:date"/>
                        </xs:sequence>
                        <xs:assert test="NgayTra >= NgayThue"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="keyKhachHang">
            <xs:selector xpath="KhachHang"/>
            <xs:field xpath="MaKH"/>
        </xs:key>
        <xs:key name="keyLoaiSach">
            <xs:selector xpath="LoaiSach"/>
            <xs:field xpath="MaLoai"/>
        </xs:key>
        <xs:key name="keySach">
            <xs:selector xpath="Sach"/>
            <xs:field xpath="MaSach"/>
        </xs:key>
        <xs:key name="keyThueSach">
            <xs:selector xpath="ThueSach"/>
            <xs:field xpath="NgayThue"/>
            <xs:field xpath="MaSach"/>
            <xs:field xpath="MaKH"/>
        </xs:key>
        <xs:keyref name="KhachHang-ThueSach" refer="keyKhachHang">
            <xs:selector xpath="ThueSach"/>
            <xs:field xpath="MaKH"/>
        </xs:keyref>
        <xs:keyref name="Sach-ThueSach" refer="keySach">
            <xs:selector xpath="ThueSach"/>
            <xs:field xpath="MaSach"/>
        </xs:keyref>
    </xs:element>
</xs:schema>

=== ttngocson/OxygenXMLEditor/Thi/QLSach.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="QLSach.xsl"?>
<QLSach xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="QLSach.xsd">
    <KhachHang>
        <MaKH>KH001</MaKH>
        <HoDemKH>Khương </HoDemKH>
        <TenKH>Vy</TenKH>
        <NgaySinh>1981-05-04</NgaySinh>
        <DiaChi>Ninh Hòa</DiaChi>
        <DienThoai>0123456</DienThoai>
    </KhachHang>
    <KhachHang>
        <MaKH>KH002</MaKH>
        <HoDemKH>Nguyễn </HoDemKH>
        <TenKH>Hiếu</TenKH>
        <NgaySinh>1980-05-04</NgaySinh>
        <DiaChi>Ninh Hòa</DiaChi>
        <DienThoai>0123456</DienThoai>
    </KhachHang>
    <KhachHang>
        <MaKH>KH003</MaKH>
        <HoDemKH>Nguyễn </HoDemKH>
        <TenKH>Đạt</TenKH>
        <NgaySinh>1979-05-04</NgaySinh>
        <DiaChi>Ninh Hòa</DiaChi>
        <DienThoai>0123456</DienThoai>
    </KhachHang>
    <KhachHang>
        <MaKH>KH004</MaKH>
        <HoDemKH>Trần </HoDemKH>
        <TenKH>Sơn</TenKH>
        <NgaySinh>1979-05-04</NgaySinh>
        <DiaChi>Dak Lak</DiaChi>
        <DienThoai>0123456</DienThoai>
    </KhachHang>
    <KhachHang>
        <MaKH>KH005</MaKH>
        <HoDemKH>Nguyễn </HoDemKH>
        <TenKH>Quang</TenKH>
        <NgaySinh>1982-05-04</NgaySinh>
        <DiaChi>Nha Trang</DiaChi>
        <DienThoai>0123456</DienThoai>
    </KhachHang>
    <LoaiSach>
        <MaLoai>L01</MaLoai>
        <TenLoai>Sách thiếu nhi</TenLoai>
    </LoaiSach>
    <LoaiSach>
        <MaLoai>L02</MaLoai>
        <TenLoai>Sách nội trợ</TenLoai>
    </LoaiSach>
    <LoaiSach>
        <MaLoai>L03</MaLoai>
        <TenLoai>Sách tài liệu</TenLoai>
    </LoaiSach>
    <LoaiSach>
        <MaLoai>L04</MaLoai>
        <TenLoai>Sách khoa học</TenLoai>
    </LoaiSach>
    <LoaiSach>
        <MaLoai>L05</MaLoai>
        <TenLoai>Sách tham khảo</TenLoai>
    </LoaiSach>
    <Sach>
        <MaSach>S001</MaSach>
        <TenSach>Đôrêmon</TenSach>
        <MaLoai>L01</MaLoai>
        <GiaThue>500</GiaThue>
    </Sach>
    <Sach>
        <MaSach>S002</MaSach>
        <TenSach>Các món ăn Việt Nam</TenSach>
        <MaLoai>L02</MaLoai>
        <GiaThue>1000</GiaThue>
    </Sach>
    <Sach>
        <MaSach>S003</MaSach>
        <TenSach>Chiến thắng Điện Biên Phủ</TenSach>
        <MaLoai>L03</MaLoai>
        <GiaThue>1500</GiaThue>
    </Sach>
    <Sach>
        <MaSach>S004</MaSach>
        <TenSach>Khám phá ngân hà</TenSach>
        <MaLoai>L04</MaLoai>
        <GiaThue>2000</GiaThue>
    </Sach>
    <Sach>
        <MaSach>S005</MaSach>
        <TenSach>Sách giải toán</TenSach>
        <MaLoai>L05</MaLoai>
        <GiaThue>2500</GiaThue>
    </Sach>
    <ThueSach>
        <NgayThue>2019-05-04</NgayThue>
        <MaSach>S003</MaSach>
        <MaKH>KH003</MaKH>
        <NgayTra>2019-05-09</NgayTra>
    </ThueSach>
    <ThueSach>
        <NgayThue>2019-05-03</NgayThue>
        <MaSach>S002</MaSach>
        <MaKH>KH001</MaKH>
        <NgayTra>2019-05-06</NgayTra>
    </ThueSach>
    <ThueSach>
        <NgayThue>2019-05-04</NgayThue>
        <MaSach>S003</MaSach>
        <MaKH>KH001</MaKH>
        <NgayTra>2019-05-08</NgayTra>
    </ThueSach>
    <ThueSach>
        <NgayThue>2019-05-04</NgayThue>
        <MaSach>S002</MaSach>
        <MaKH>KH002</MaKH>
        <NgayTra>2019-05-10</NgayTra>
    </ThueSach>
    <ThueSach>
        <NgayThue>2019-05-04</NgayThue>
        <MaSach>S004</MaSach>
        <MaKH>KH002</MaKH>
        <NgayTra>2019-05-07</NgayTra>
    </ThueSach>
</QLSach>
